import fs from 'fs';
import path from 'path';
import os from 'os';
import crypto from 'crypto';
import { activeStore } from '../pipeline/store.js';
import { isSafeWorkspacePath } from './workspaceSecurity.js';
import { openInVSCode } from './vscodeService.js';
import { createWorkspaceBaseline, checkWorkspaceChanges } from './workspaceStatus.js';

/**
 * Creates or ensures modern & legacy workspaces on disk for single-file or project session
 */
export function ensureWorkspaceForSession() {
  const session = activeStore.getSession();
  if (!session) return null;

  const sessionId = session.id || crypto.randomBytes(8).toString('hex');
  const sessionDir = path.join(os.tmpdir(), 'latentcode', 'sessions', sessionId);
  const legacyDir = session.legacyWorkspace || path.join(sessionDir, 'legacy');
  const modernDir = session.modernWorkspace || path.join(sessionDir, 'modern');

  fs.mkdirSync(legacyDir, { recursive: true });
  fs.mkdirSync(modernDir, { recursive: true });

  // 1. Ensure Legacy Workspace contains raw code if single file
  if (session.rawCode && !fs.existsSync(path.join(legacyDir, session.filename || 'legacy-code.js'))) {
    fs.writeFileSync(path.join(legacyDir, session.filename || 'legacy-code.js'), session.rawCode);
  }

  // 2. Ensure Modern Workspace contains generated modernized code if completed
  if (session.projectDiff && Array.isArray(session.projectDiff) && session.projectDiff.length > 0) {
    // Multi-file project diff writing
    session.projectDiff.forEach(fileItem => {
      const relPath = fileItem.filename || fileItem.path || fileItem.name;
      const content = fileItem.content || fileItem.code || fileItem.migratedContent;
      if (relPath && content) {
        const fullPath = path.join(modernDir, relPath);
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });
        fs.writeFileSync(fullPath, content);
      }
    });
  } else if (session.migratedCode) {
    // Single-file modernized component writing
    const filename = session.filename || 'MigratedComponent.jsx';
    const compName = path.basename(filename, path.extname(filename));
    const srcDir = path.join(modernDir, 'src', 'components');
    fs.mkdirSync(srcDir, { recursive: true });

    const targetComponentPath = path.join(srcDir, `${compName}.jsx`);
    fs.writeFileSync(targetComponentPath, session.migratedCode);

    // App entry point in modern workspace
    const appJsx = `import React from 'react';
import ${compName} from './components/${compName}';

/**
 * Modernized React Application
 * Generated by Legacy Rescue Engine
 */
export default function App() {
  return (
    <div className="p-8 font-sans bg-slate-950 text-slate-100 min-h-screen">
      <${compName} />
    </div>
  );
}`;
    fs.writeFileSync(path.join(modernDir, 'src', 'App.jsx'), appJsx);

    // package.json in modern workspace
    fs.writeFileSync(
      path.join(modernDir, 'package.json'),
      JSON.stringify({
        name: 'migrated-project',
        version: '1.0.0',
        dependencies: {
          react: '^18.2.0',
          'react-dom': '^18.2.0'
        }
      }, null, 2)
    );
  }

  const baseline = createWorkspaceBaseline(modernDir);
  activeStore.setWorkspace(sessionId, legacyDir, modernDir, baseline);

  return modernDir;
}

/**
 * Resolves the target workspace for VS Code launch.
 * MUST open modernWorkspace when migration is complete.
 */
export async function openWorkspaceInVSCode(sessionIdReq, sessionDataReq = null) {
  // If sessionDataReq is provided (from restored browser state or history item), sync activeStore
  if (sessionDataReq && sessionDataReq.migratedCode) {
    const targetSessionId = sessionDataReq.id || sessionIdReq || `session-${Date.now()}`;
    const sessionDir = path.join(os.tmpdir(), 'latentcode', 'sessions', targetSessionId);
    const legacyWorkspace = sessionDataReq.legacyWorkspace || path.join(sessionDir, 'legacy');
    const modernWorkspace = sessionDataReq.modernWorkspace || path.join(sessionDir, 'modern');

    activeStore.setWorkspace(targetSessionId, legacyWorkspace, modernWorkspace);
    activeStore.setAnalysis(
      sessionDataReq.filename || 'legacy-code.js',
      sessionDataReq.rawCode || '',
      sessionDataReq.analysis || {}
    );
    if (sessionDataReq.plan) activeStore.setPlan(sessionDataReq.plan);
    activeStore.setMigration(
      sessionDataReq.migratedCode,
      sessionDataReq.projectDiff || sessionDataReq.migrationSummary
    );
    if (sessionDataReq.verification) activeStore.setVerification(sessionDataReq.verification);
  }

  let session = activeStore.getSession();

  // 1. Session Existence Check
  if (!session || (!session.id && !session.rawCode && !session.workspaceDir)) {
    return {
      success: false,
      statusCode: 404,
      error: 'SESSION_NOT_FOUND',
      message: 'Active migration session not found.'
    };
  }

  // 2. Validate session ID if provided (allow matching if restored)
  if (sessionIdReq && session.id && sessionIdReq !== session.id && !sessionDataReq) {
    return {
      success: false,
      statusCode: 403,
      error: 'INVALID_SESSION_ID',
      message: 'Session ID mismatch.'
    };
  }

  // 3. Check migration completion
  const isMigrationComplete = Boolean(session.migratedCode || session.verificationResult || session.projectDiff);

  if (!isMigrationComplete) {
    return {
      success: false,
      statusCode: 400,
      error: 'MIGRATION_NOT_COMPLETE',
      message: 'Modernized workspace is not available. Please run the migration first.'
    };
  }

  // Ensure modern workspace exists on disk with generated files
  const modernWorkspace = ensureWorkspaceForSession();

  // 4. Validate modern workspace directory existence
  if (!modernWorkspace || !fs.existsSync(modernWorkspace) || !fs.statSync(modernWorkspace).isDirectory()) {
    return {
      success: false,
      statusCode: 404,
      error: 'MODERN_WORKSPACE_NOT_FOUND',
      message: 'Modernized workspace is unavailable. Please run the migration again.'
    };
  }

  // 5. Confirm modern workspace contains generated files
  let contents = [];
  try {
    contents = fs.readdirSync(modernWorkspace);
  } catch (_) {}

  if (contents.length === 0) {
    return {
      success: false,
      statusCode: 404,
      error: 'MODERN_WORKSPACE_EMPTY',
      message: 'Modernized workspace is unavailable. Please run the migration again.'
    };
  }

  // 6. Security Path Check
  if (!isSafeWorkspacePath(modernWorkspace)) {
    return {
      success: false,
      statusCode: 400,
      error: 'WORKSPACE_INVALID',
      message: 'Migration workspace path validation failed.'
    };
  }

  // 7. Launch VS Code on modern workspace ONLY
  try {
    const result = await openInVSCode(modernWorkspace);
    return {
      success: true,
      statusCode: 200,
      workspaceOpened: modernWorkspace,
      message: result.message
    };
  } catch (err) {
    return {
      success: false,
      statusCode: 500,
      error: err.error || 'VSCODE_LAUNCH_FAILED',
      message: err.message || 'Failed to launch VS Code'
    };
  }
}

export function getWorkspaceStatus(sessionIdReq) {
  const session = activeStore.getSession();

  if (!session || (!session.workspaceDir && !session.migratedCode)) {
    return {
      success: false,
      statusCode: 404,
      error: 'SESSION_NOT_FOUND',
      message: 'Active migration session or workspace not found.'
    };
  }

  const workspaceDir = session.modernWorkspace || session.workspaceDir || ensureWorkspaceForSession();

  if (!workspaceDir || !fs.existsSync(workspaceDir)) {
    return {
      success: false,
      statusCode: 404,
      error: 'MIGRATION_WORKSPACE_NOT_FOUND',
      message: 'The migrated workspace could not be found.'
    };
  }

  const result = checkWorkspaceChanges(workspaceDir, session.workspaceBaseline);
  return {
    success: true,
    statusCode: 200,
    changed: result.changed,
    filesChanged: result.filesChanged
  };
}
